## Numpy array and basics
---
### learn about numpy self-study

- First of all we have to initialize virtual environment
- Then to install numpy we have to run "pip install numpy" in terminal

- Now we are importing numpy 

In [5]:
import numpy as np
import time

### Creating array(vector) with 'numpy'

In [6]:
arr_1d = np.array([1,2,3,4,5])
print("1d array : ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2d array : ", arr_2d)

1d array :  [1 2 3 4 5]
2d array :  [[1 2 3]
 [4 5 6]]


### list vs numpy array
numpy array is superior to python list 

In [6]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)
print(type(py_list))

np_array = np.array([1,2,3])
print("Python array multiplication ", np_array * 2)
print(type(np_array))

Python list multiplication  [1, 2, 3, 1, 2, 3]
<class 'list'>
Python array multiplication  [2 4 6]
<class 'numpy.ndarray'>


### Regular python operation time VS numpy operation time

In [7]:
startTime = time.time()

py_list = [i*2 for i in range(100000000)]

endTime = time.time()
print(f"regular list operation time = {endTime - startTime}")


startTime = time.time()
np_array = np.arange(100000000) * 2
endTime = time.time()
print(f"numpy list operation time = {endTime - startTime}")

regular list operation time = 5.494737386703491
numpy list operation time = 0.4731876850128174


### numpy multi dimentional array

In [12]:
nparray2d = np.array([[11,12,13],
                      [21,22,23],
                      [31,32,33]])

nparray3d = np.array([[[11,12,13], [21,22,23], [31,32,33]],
                      [[11,12,13], [21,22,23], [31,32,33]]])

print(f"dimentions of the array = {nparray2d.ndim}")
print(f"dimentions of the array = {nparray3d.ndim}")

# print(nparray2d)
# print(nparray2d.shape)

print(nparray3d)
# print(nparray3d.shape)

dimentions of the array = 2
dimentions of the array = 3
[[[11 12 13]
  [21 22 23]
  [31 32 33]]

 [[11 12 13]
  [21 22 23]
  [31 32 33]]]


### Creating array from scratch

In [15]:
zeros = np.zeros((3, 4))  #it creates a metrics of 0s of 3 row 4 coloum ()-for tuple
print("zeros array : \n",zeros)

ones = np.ones((3, 4))  # its similar to above and  []for list,()for tuple
print("ones array : \n",ones)

fulls = np.full((3,4), 7)
print("array of constant element : \n",fulls)

randoms = np.random.random((3, 4))
print("random array :\n",randoms)

sequence = np.arange(0, 10, 2)
print("sequence array :\n",sequence)

zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array of constant element : 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random array :
 [[0.8044965  0.49032644 0.60570303 0.91956441]
 [0.41741888 0.61606357 0.29348143 0.05765634]
 [0.73119661 0.19967671 0.2851732  0.69710792]]
sequence array :
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [ ]:
vector = np.array([1,2,3,4])
print("vector :\n",vector)

matrix = np.array([[1,2,3], #2d arrays are called matrix
                   [4,5,6],
                   [7,8,9]])
print("matrix :\n",matrix)

tensor = np.array([[[1,2],[3,4]],      #lager then 2d arrays are called tensor
                   [[5,6],[7,8]]])
print("tensor : \n",tensor)

vector :
 [1 2 3 4]
matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape :",arr.shape)
print("Dimention :",arr.ndim)
print("Size :",arr.size)
print("Datatype :",arr.dtype)

Shape : (2, 3)
Dimention : 2
Size : 6
Datatype : int64


### Array reshaping

In [19]:
arr = np.arange(12)
print("Original array : ",arr)

reshaped = arr.reshape((3,4))
print("Reshaped array : \n",reshaped)

# flatten(returns copy, instade of view/original)
flattened = reshaped.flatten()
print("Flattened array :",flattened)

# ravel (return view/original, instead of copy)
raveled = reshaped.ravel()
print("Raveled array : ",raveled)

# transpose
transpose = reshaped.T
print("Transpose : \n",transpose)

print("Original array : ",arr)

Original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
