## Advance Operation with Buisness Example
---

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
# Data structure: [resturant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],    # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],    # Beijing Bites
    [3, 200000, 230000, 260000, 300000],    # Pizza Hub
    [4, 180000, 210000, 240000, 270000],    # Burger Point
    [5, 160000, 185000, 205000, 230000]     # Chai Point
])


print("==== Zomato sales analysis ====")

print("\n Sales data shape : ", sales_data.shape)
print("\n Sample data for 1st 3 resturant : \n", sales_data[0:3])
# print("\n Sample data for 1st 3 resturant : \n", sales_data[: , 1:])

==== Zomato sales analysis ====

 Sales data shape :  (5, 5)

 Sample data for 1st 3 resturant : 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


### Total sales per year :-

In [13]:
# YEARLY TOTAL SALES CALCULATION
# print(np.sum(sales_data, axis=0))
yearly_total = np.sum(sales_data[: , 1:], axis=0)
print("Yearly total sales : ", yearly_total)

# MINIMUM SALES PER RESTURENT 
min_sales = np.min(sales_data[: , 1:], axis=1)
print("Minimum sales per resturent : ", min_sales)

Yearly total sales :  [ 810000  945000 1085000 1240000]
Minimum sales per resturent :  [150000 120000 200000 180000 160000]
