## Numpy Array Operations
---

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing : ", arr[1:10:2])
print("Negative indexing : ", arr[-3])

Basic Slicing :  [ 2  4  6  8 10]
Negative indexing :  8


In [4]:
arr_2d = np.array([[11,12,13],
                   [21,22,23],
                   [31,32,33]])

print("Specific Element : ", arr_2d[1,2])
print("Entire Row : ", arr_2d[1])
print("Entire Row : ", arr_2d[:,2])

Specific Element :  23
Entire Row :  [21 22 23]
Entire Row :  [13 23 33]


## Sorting
---

In [5]:
unsorted = np.array([3,1,4,5,9,6,2])
# REGULAR SORTING
print("sorted array : ", np.sort(unsorted))

# 2D ARRAY SORTING
arr_2d_unsorted = np.array([[3,1],[2,1],[2,3]])
print("Sorted 2d array by column : \n", np.sort(arr_2d_unsorted, axis=0))

sorted array :  [1 2 3 4 5 6 9]
Sorted 2d array by column : 
 [[2 1]
 [2 1]
 [3 3]]


## Filtering
---

In [6]:
nums = np.arange(11)
print("Unfiltered : ", nums)

even_nums = nums[nums % 2 == 0]
print("Fintered : ", even_nums)

Unfiltered :  [ 0  1  2  3  4  5  6  7  8  9 10]
Fintered :  [ 0  2  4  6  8 10]


## Filter with mask
---
mask stores the whole expression for evaluation 

In [7]:
mask = nums > 5
print("Number greater than 5 : ", nums[mask])

Number greater than 5 :  [ 6  7  8  9 10]


## Fancy indexing vs np.where()
---

In [8]:
indices = [0, 2, 4]
print(nums[indices])


where_result = np.where(nums > 5)
print("numpy where : ", nums[where_result])

[0 2 4]
numpy where :  [ 6  7  8  9 10]


In [10]:
condition_array = np.where(nums > 5, nums * 4, nums)
print(condition_array)

[ 0  1  2  3  4  5 24 28 32 36 40]


## Adding and removing data
---

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# combined = arr1 + arr2    #dont do this
combined = np.concatenate((arr1, arr2))
print(combined)

[5 7 9]
