### Broadcasting in numpy

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.random.rand(3, 3)
array3 = np.zeros((4, 4))

### to save any data in a file(database)

In [ ]:
np.save('array1.npy', array1)
np.save('array2.npy', array2)
np.save('array3.npy', array3)

### load the previously saved data 

In [7]:
loaded_array1 = np.load('array1.npy')
print("Loaded array 1 from file : \n", loaded_array1)
loaded_array2 = np.load('array2.npy')
print("Loaded array 2 from file : \n", loaded_array2)
loaded_array3 = np.load('array3.npy')
print("Loaded array 3 from file : \n", loaded_array3)

Loaded array 1 from file : 
 [[1 2 3]
 [4 5 6]]
Loaded array 2 from file : 
 [[0.17062302 0.76659268 0.8720801 ]
 [0.99290893 0.67508468 0.54838342]
 [0.72027541 0.6285481  0.27760734]]
Loaded array 3 from file : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# plot numpy logo
try:
    logo = np.load('numpy-logo.npy')
    # Display
    plt.figure(figsize=(10, 5))
    plt.Subplot(121)
    plt.imshow(logo)
    plt.title("Numpy logo")
    plt.grid(False)
    
except FileNotFoundError:
    print("Numpy logo file not found")

Numpy logo file not found
